program Accounting;
// Full Accounting Advanced 5.0 SSP  
uses
  Forms,
  ToolbarFrame in '..\Src\ToolbarFrame.pas' {frameToolbar: TFrame},
  MainForm in '..\src\MainForm.pas' {MainFrm},
  MainDataMdl in '..\src\MainDataMdl.pas' {MainDM: TDataModule},
  ActicleGroupForm in '..\Src\ActicleGroupForm.pas' {ActicleGroupFrm},
  ReportInfoForm in '..\Src\ReportInfoForm.pas' {ReportInfoFrm},
  BeginAccountForm in '..\src\BeginAccountForm.pas' {BeginAccountFrm},
  CustumizeIntefaceForm in '..\src\Giaodien\CustumizeIntefaceForm.pas' {FormCustumizeInteface},
  DMInterface in '..\src\Giaodien\DMInterface.pas' {InterfaceDM: TDataModule},
  Functions in '..\src\Giaodien\Functions.pas',
  GlobalInterface in '..\src\Giaodien\GlobalInterface.pas',
  TemplateDocForm in '..\src\TemplateDocForm.pas' {TemplateDocFrm},
  RegAutoOutForm in '..\Src\RegAutoOutForm.pas' {RegAutoOutFrm},
  WorkListForm in '..\Src\WorkListForm.pas' {WorkListFrm},
  CostUnfinishForm in '..\Src\CostUnfinishForm.pas' {CostUnfinishFrm},
  PopupForm in '..\src\PopupForm.pas' {PopupFrm},
  MsgDlgForm in '..\src\MsgDlgForm.pas' {MsgDlgFrm},
  ObjectTypeForm in '..\src\ObjectTypeForm.pas' {ObjectTypeFrm},
  DocTypeInfoForm in '..\Src\DocTypeInfoForm.pas' {DocTypeInfoFrm},
  dxTreeGridMenus in '..\src\dxTreeGridMenus.pas',
  TinhGTSPForm in '..\src\TinhGTSPForm.pas' {TinhGTSPFrm},
  AssetHistoryForm in '..\src\AssetHistoryForm.pas' {AssetHistoryFrm},
  ParamsForm in '..\src\ParamsForm.pas' {ParamsFrm},
  RateForm in '..\src\RateForm.pas' {RateFrm},
  EntrysForm in '..\src\EntrysForm.pas' {EntrysFrm},
  GlobalUnit in '..\src\GlobalUnit.pas',
  FactorArise in '..\Src\FactorArise.pas' {FactorlAriseFrm},
  BeginForeign in '..\src\BeginForeign.pas' {BeginForeignFrm},
  OptionForm in '..\src\OptionForm.pas' {OptionFrm},
  RegAllocateForm in '..\src\RegAllocateForm.pas' {RegAllocateFrm},
  SearchForm in '..\src\SearchForm.pas' {SearchFrm},
  SimpleSecurityLibrary in '..\src\SimpleSecurityLibrary.pas',
  DefEntrysForm in '..\Src\DefEntrysForm.pas' {DefEntrysFrm},
  AssetListForm in '..\src\AssetListForm.pas' {AssetListFrm},
  TemplateListForm in '..\src\TemplateListForm.pas' {TemplateListFrm},
  PlanPriceForm in '..\src\PlanPriceForm.pas' {PlanPriceFrm},
  OtherNormForm in '..\src\OtherNormForm.pas' {OtherNormFrm},
  ButtoanCTGSForm in '..\Src\ButtoanCTGSForm.pas' {ButtoanCTGSFrm},
  RegTransferForm in '..\src\RegTransferForm.pas' {RegTransferFrm},
  TonghopForm in '..\src\TonghopForm.pas' {TonghopFrm},
  SalePriceForm in '..\src\SalePriceForm.pas' {SalePriceFrm},
  AccountAriseNT in '..\src\AccountAriseNT.pas' {AccountAriseNTFrm},
  HSCTForm in '..\src\HSCTForm.pas' {HSCTFrm},
  SoduTKForm in '..\src\SoduTKForm.pas' {SoduTKFrm},
  ChgNumToStr in '..\src\ChgNumToStr.pas',
  ErrorListForm in '..\src\ErrorListForm.pas' {ErrorListFrm},
  DefDKBCDKTForm in '..\Src\DefDKBCDKTForm.pas' {DefDKBCDKTFrm},
  BeginGoodObj in '..\Src\BeginGoodObj.pas' {BeginGoodObjFrm},
  RentAriseCT in '..\Src\RentAriseCT.pas' {RentAriseCTFrm},
  SelectAccForm in '..\src\SelectAccForm.pas' {SelectAccFrm},
  ReplaceForm in '..\Src\ReplaceForm.pas' {ReplaceFrm},
  CaptionListForm in '..\Src\CaptionListForm.pas' {CaptionListFrm},
  DefRptKQHDKDBForm in '..\src\DefRptKQHDKDBForm.pas' {DefRptKQHDKDBFrm: TForm},
  DefRptKQHDKDForm in '..\Src\DefRptKQHDKDForm.pas' {DefRptKQHDKDFrm: TForm},
  BeginAssetForm in '..\src\BeginAssetForm.pas' {BeginAssetFrm: TForm},
  BalFactorForeign in '..\Src\BalFactorForeign.pas' {BalFactorForeignFrm: TForm},
  RestoreForm in '..\Src\RestoreForm.pas' {RestoreFrm: TForm},
  ReportForm in '..\Src\ReportForm.pas' {ReportFrm: TForm},
  InvoiceForm in '..\src\InvoiceForm.pas' {InvoiceFrm: TForm},
  TonghopCPGTForm in '..\Src\TonghopCPGTForm.pas' {TonghopCPGTFrm: TForm},
  GroupListForm in '..\src\GroupListForm.pas' {GroupListFrm: TForm},
  DocLogForm in '..\src\DocLogForm.pas' {DocLogFrm: TForm},
  SearchDlgForm in '..\src\SearchDlgForm.pas' {SearchDlgFrm},
  KQHDKDCondForm in '..\Src\KQHDKDCondForm.pas' {KQHDKDCondFrm},
  DocListForm in '..\src\DocListForm.pas' {DocListFrm},
  AssetAriseForm in '..\src\AssetAriseForm.pas' {AssetAriseFrm},
  AccountListForm in '..\src\AccountListForm.pas' {AccountListFrm},
  UserManagerForm in '..\src\UserManagerForm.pas' {UserManagerFrm},
  UserForm in '..\src\UserForm.pas' {UserFrm},
  ImportForm in '..\src\ImportForm.pas' {ImportFrm},
  ThongkeHMForm in '..\src\ThongkeHMForm.pas' {ThongkeHMFrm},
  ThongkeBALForm in '..\Src\ThongkeBALForm.pas' {ThongkeBALFrm},
  Thongke10KHForm in '..\Src\Thongke10KHForm.pas' {Thongke10KHFrm},
  ThongkeTKForm in '..\src\ThongkeTKForm.pas' {ThongkeTKFrm},
  GenDocForm in '..\src\GenDocForm.pas' {GenDocFrm},
  ThongkeTKPSForm in '..\src\ThongkeTKPSForm.pas' {ThongkeTKPSFrm},
  DocTempForm in '..\Src\DocTempForm.pas' {DocTempFrm},
  ThongbaoForm in '..\Src\ThongbaoForm.pas' {ThongBaoFrm},
  AssetForm in '..\Src\AssetForm.pas' {AssetFrm},
  DocTypeForm in '..\Src\DocTypeForm.pas' {DocTypeFrm},
  InOutTypeForm in '..\Src\InOutTypeForm.pas' {InOutTypeFrm},
  DocFullForm in '..\Src\DocFullForm.pas' {DocFullFrm},
  FinStardardForm in '..\Src\FinStardardForm.pas' {FinStardardFrm},
  InstockForm in '..\Src\InstockForm.pas' {InstockFrm},
  ObjectDetailForm in '..\Src\ObjectDetailForm.pas' {ObjectDetailFrm},
  MessageForm in '..\Src\MessageForm.pas' {MessageFrm},
  RegForBillForm in '..\Src\RegForBillForm.pas' {RegForBillFrm},
  AnalysisFrm in '..\Src\AnalysisFrm.pas' {AnalystFrm},
  NhatKySoCaiForm in '..\Src\NhatKySoCaiForm.pas' {NhatKySoCaiFrm},
  BalObjFactorForm in '..\Src\BalObjFactorForm.pas' {BalObjFactorFrm},
  InOutForm in '..\Src\InOutForm.pas' {InOutFrm},
  InstockWare in '..\Src\InstockWare.pas' {InstockWareFrm},
  AccDetailArise in '..\Src\AccDetailArise.pas' {AccDetailAriseFrm},
  ChildAccDetailForm in '..\Src\ChildAccDetailForm.pas' {ChildAccDetailFrm},
  AccDetailForm in '..\Src\AccDetailForm.pas' {AccDetailFrm},
  AccountArise in '..\Src\AccountArise.pas' {AccountAriseFrm},
  RptParamForm in '..\Src\RptParamForm.pas' {RptParamFrm},
  CPDodangForm in '..\Src\CPDodangForm.pas' {CPDodangFrm},
  GroupMatNormForm in '..\Src\GroupMatNormForm.pas' {GroupMatNormFrm},
  ProductInfoForm in '..\Src\ProductInfoForm.pas' {ProductInfoFrm},
  MsgListForm in '..\Src\MsgListForm.pas' {MsgListFrm},
  ObjDocBalForm in '..\Src\ObjDocBalForm.pas' {ObjDocBalFrm},
  ObjectForm in '..\Src\ObjectForm.pas' {ObjectFrm},
  HeSoDoiHangForm in '..\Src\HeSoDoiHangForm.pas' {HeSoDoiHangFrm},
  ObjDocBeginBalForm in '..\Src\ObjDocBeginBalForm.pas' {ObjDocBeginBalFrm},
  BalDetailForeign in '..\Src\BalDetailForeign.pas' {BalForeignFrm},
  AccDetailAriseNT in '..\Src\AccDetailAriseNT.pas' {AccDetailAriseNTFrm},
  FactorDetailForm in '..\Src\FactorDetailForm.pas' {FactorDetailFrm},
  GenDocDMForm in '..\Src\GenDocDMForm.pas' {GenDocDMFrm},
  FactorAriseNT in '..\Src\FactorAriseNT.pas' {FactorlAriseNTFrm},
  ActicleAriseForm in '..\Src\ActicleAriseForm.pas' {ActicleAriseFrm},
  TAPHOPCHIPHIForm in '..\Src\TAPHOPCHIPHIForm.pas' {TAPHOPCHIPHIFrm},
  PrmBalanceConditionForm in '..\Src\PrmBalanceConditionForm.pas' {PrmBalanceConditionFrm},
  DefRptLCTTForm in '..\Src\DefRptLCTTForm.pas' {DefRptLCTTFrm},
  LCTTCondForm in '..\Src\LCTTCondForm.pas' {LCTTCondFrm},
  ActicleCompareForm in '..\Src\ActicleCompareForm.pas' {ActicleCompareFrm},
  LabourNormForm in '..\Src\LabourNormForm.pas' {LabourFrm},
  InvoiceListForm in '..\Src\InvoiceListForm.pas' {InvoiceListFrm},
  AccBalDetail in '..\Src\AccBalDetail.pas' {AccBalDetailFrm},
  DefRptTHKQHDKDFrm in '..\Src\DefRptTHKQHDKDFrm.pas' {FrmDefRptTHKQHD},
  DK_THKQHDKDFrm in '..\Src\DK_THKQHDKDFrm.pas' {FrmDK_THKQHDKD},
  DK_KQKDFrm in '..\Src\DK_KQKDFrm.pas' {FrmDK_KQKD},
  DefRptKQKDFrm in '..\Src\DefRptKQKDFrm.pas' {FrmDefRptKQKD},
  TMBCTC_37Form in '..\Src\TMBCTC_37Form.pas' {TMBCTC_37Frm},
  TMBCTC_4CondForm in '..\Src\TMBCTC_4CondForm.pas' {TMBCTC_4CondFrm},
  TMBCTC_4Form in '..\Src\TMBCTC_4Form.pas' {TMBCTC_4Frm},
  TMBCTC_35Form in '..\Src\TMBCTC_35Form.pas' {TMBCTC_35Frm},
  TMBCTC_36Form in '..\Src\TMBCTC_36Form.pas' {TMBCTC_36Frm},
  md5 in '..\Src\md5.pas',
  ScriptForm in '..\Src\ScriptForm.pas' {ScriptFrm},
  QuestionForm in '..\Src\QuestionForm.pas' {QuestionFrm},
  AccOptForm in '..\Src\AccOptForm.pas' {AccOptFrm},
  ObjGrpForm in '..\Src\ObjGrpForm.pas' {ObjGrpFrm},
  ParamBalanceForm in '..\Src\ParamBalanceForm.pas' {ParamBalanceFrm},
  ParamArisingForm in '..\Src\ParamArisingForm.pas' {ParamArisingFrm},
  PrmArisingConditionForm in '..\Src\PrmArisingConditionForm.pas' {PrmArisingConditionFrm},
  SQLTesterForm in '..\Src\SQLTesterForm.pas' {SQLTesterFrm},
  SQLParamsForm in '..\Src\SQLParamsForm.pas' {SQLParamsFrm},
  SoCaiHMKP in '..\Src\SoCaiHMKP.pas' {SoCaiHMKPFrm},
  BarCodeForTax in '..\Src\BarCodeForTax.pas',
  DefRptBCDKTForm in '..\Src\DefRptBCDKTForm.pas' {DefRptBCDKTFrm},
  HESOPBCPGTForm in '..\Src\HESOPBCPGTForm.pas' {HESOPBCPGTFrm},
  CHITIETPBSPForm in '..\Src\CHITIETPBSPForm.pas' {CHITIETPBSPFrm},
  KETQUAPBCPForm in '..\Src\KETQUAPBCPForm.pas' {KETQUAPBCPFrm},
  CHITIETCHIPHIForm in '..\Src\CHITIETCHIPHIForm.pas' {CHITIETCHIPHIFrm},
  CHITIETPHANBOForm in '..\Src\CHITIETPHANBOForm.pas' {CHITIETPHANBOFrm},
  CurrencyForm in '..\Src\CurrencyForm.pas' {CurrencyFrm},
  KQHDKDCondBForm in '..\Src\KQHDKDCondBForm.pas' {KQHDKDCondBFrm},
  VATTypeForm in '..\Src\VATTypeForm.pas' {VATTypeFrm},
  MaterialNormForm in '..\Src\MaterialNormForm.pas' {MaterialNormFrm},
  GenAutoDocForm in '..\Src\GenAutoDocForm.pas' {GenAutoDocFrm},
  SplashForm in '..\Src\Splash\SplashForm.pas' {SplashFrm},
  PromotionScaleForm in '..\Src\PromotionScaleForm.pas' {PromotionScaleFrm},
  ChungtuGhisoForm in '..\Src\ChungtuGhisoForm.pas' {ChungtuGhisoFrm},
  LoginForm in '..\Src\LoginForm.pas' {LoginFrm},
  ProductForm in '..\Src\ProductForm.pas' {ProductFrm},
  WarehouseForm in '..\Src\WarehouseForm.pas' {WarehouseFrm},
  ActicleForm in '..\Src\ActicleForm.pas' {ActicleFrm},
  ActiclePlanForm in '..\Src\ActiclePlanForm.pas' {ActiclePlanFrm},
  LookupFrm in '..\Src\LookupFrm.pas' {Lookup},
  ThongkeTCForm in '..\Src\ThongkeTCForm.pas' {ThongkeTCFrm},
  NhapTraLaiForm in '..\Src\NhapTraLaiForm.pas' {NhapTraLaiFrm},
  AutoEntryForm in '..\Src\AutoEntryForm.pas' {AutoEntryFrm},
  ObjectSubValForm in '..\Src\ObjectSubValForm.pas' {ObjectSubValFrm},
  OutDetailForm in '..\Src\OutDetailForm.pas' {OutDetailFrm},
  BuyPriceForm in '..\Src\BuyPriceForm.pas' {BuyPriceFrm},
  AutoRateForm in '..\Src\AutoRateForm.pas' {AutoRateFrm},
  ConfigFrm in '..\Src\ConfigFrm.pas' {frmConfig},
  AutoTypesForm in '..\Src\AutoTypesForm.pas' {AutoTypesFrm},
  ObjectSubInfoForm in '..\Src\ObjectSubInfoForm.pas' {ObjectSubInfoFrm},
  ObjectSubValueForm in '..\Src\ObjectSubValueForm.pas' {ObjectSubValueFrm},
  ChangePass in '..\Src\ChangePass.pas' {ChangePassFrm},
  InvoiceTypeForm in '..\Src\InvoiceTypeForm.pas' {InvoiceTypeFrm},
  CM_Functions in '..\Src\Common\CM_Functions.pas',
  DBFunctions in '..\Src\Common\DBFunctions.pas',
  CM_PopupForm in '..\Src\Common\CM_PopupForm.pas' {CM_PopupFrm},
  ReportListForm in '..\Src\ReportListForm.pas' {frmReportList},
  AboutForm in '..\Src\AboutForm.pas' {AboutFrm},
  DocTypeRuleForm in '..\Src\DocTypeRuleForm.pas' {DocTypeRuleFrm},
  BudgetForm in '..\Src\BudgetForm.pas' {BudgetFrm},
  FormKTBCD in '..\Src\FormKTBCD.pas' {KTBCDForm},
  KTTKNNForm in '..\Src\KTTKNNForm.pas' {FormKTTKNN},
  PPXKForm in '..\Src\PPXKForm.pas' {FormPPXK},
  KTTKDTForm in '..\Src\KTTKDTForm.pas' {FormKTTKDT},
  DKQuyettoanthuTNDN in '..\Src\dkquyettoanthutndn.pas' {frmDKQuyettoanthueTNDN},
  QuyettoanthueTNDN in '..\Src\quyettoanthuetndn.pas' {frmQuyettoanthueTNDN},
  ContextCompareLib in '..\Src\ContextCompareLib.pas',
  NewBackupFrm in '..\Src\NewBackupFrm.pas' {frmNewBackup},
  BalObjFactor1Form in '..\Src\BalObjFactor1Form.pas' {BalObjFactor1Frm},
  TMBCTC_DKForm in '..\Src\tmbctc_dkform.pas' {frmTMBCTC_DK},
  ThuyetminhBCTC in '..\Src\thuyetminhbctc.pas' {ThuyetminhBCTCFrm},
  THUYETMINHBCTC_DK in '..\Src\thuyetminhbctc_dk.pas' {frmThuyetminhbctc_dk},
  ThuyetminhBCTC_DKKPS in '..\Src\thuyetminhbctc_dkkps.pas' {frmThuyetminhBCTC_DKKPS},
  DefDefineBCDKTForm in '..\Src\DefDefineBCDKTForm.pas' {Form1},
  UnitForm in '..\Src\UnitForm.pas' {UnitFrm},
  UnitScaleForm in '..\Src\UnitScaleForm.pas' {UnitScaleFrm},
  ChkResultForm in '..\Src\ChkResultForm.pas' {ChkResultFrm},
  TransferReciveForm in '..\Src\TransferReciveForm.pas' {TransferReceivefrm},
  HintBoxDlg in '..\Src\HintBoxDlg.pas' {frmHintBox},
  BackupForm in '..\Src\BackupForm.pas' {BackupFrm},
  SaveRestoreDocForm in '..\Src\SaveRestoreDocForm.pas' {SaveRestoreDocFrm},
  BranchForm in '..\Src\BranchForm.pas' {BranchFrm},
  GetComID in '..\Src\GetComID.pas',
  dxDBGrid in '..\..\..\Component Unicode\ExpressQuantumGrid\Delphi 7\Sources\dxDBGrid.pas',
  tln_costdeclareform in '..\Src\tln_costdeclareform.pas' {tln_Costdeclarefrm},
  HVSKQHDKDForm in '..\Src\HVSKQHDKDForm.pas' {HVSKQHDKDFrm},
  HVSKQHDKDCond2Form in '..\Src\HVSKQHDKDCond2Form.pas' {HVSKQHDKDCond2Frm},
  HVSKQHDKDCondForm in '..\Src\HVSKQHDKDCondForm.pas' {HVSKQHDKDCondFrm},
  ImportWizardSamForm in '..\Src\ImportWizardSamForm.pas' {ImportWizardFrm},
  ImportSamForm in '..\Src\ImportSamForm.pas' {ImportSamfrm},
  DefBaocaoSamForm in '..\Src\DefBaocaoSamForm.pas' {DefBaocaoSamFrm},
  DefBaocaoSamCondForm in '..\Src\DefBaocaoSamCondForm.pas' {DefBaocaoSamCondFrm},
  ThongkeTysuatForm in '..\Src\ThongkeTysuatForm.pas' {ThongkeTysuatFrm},
  ThongkeForm in '..\Src\ThongkeForm.pas' {ThongkeFrm},
  IdleJobForm in '..\Src\IdleJobForm.pas' {IdleJobfrm},
  CNQuahanForm in '..\Src\CNQuahanForm.pas' {CNQuahanFrm},
  materialproform in '..\Src\materialproform.pas' {MaterialProFrm},
  MaterialUnfinishForm in '..\Src\MaterialUnfinishForm.pas' {MaterialUnfinishFrm},
  RegisterForm in '..\Src\RegisterForm.pas' {RegisterFrm},
  cpuid in '..\Src\cpuid.pas',
  GroupNormForm in '..\Src\GroupNormForm.pas' {GroupNormFrm},
  MaterialEstimateForm in '..\Src\MaterialEstimateForm.pas' {MaterialEstimateFrm},
  CCDCinf in '..\Src\CCDCinf.pas' {CCDCINFFrm},
  CCDCForm in '..\Src\CCDCForm.pas' {CCDCFrm},
  SSP_Library in '..\Src\SSP_Library.pas',
  XoaDLImportForm in '..\Src\XoaDLImportForm.pas' {XoaDLImportFrm},
  ReportTHCond2Form in '..\Src\ReportTHCond2Form.pas' {ReportTHCond2Frm},
  ReportTHCondForm in '..\Src\ReportTHCondForm.pas' {ReportTHCondFrm},
  ReportTHForm in '..\Src\ReportTHForm.pas' {ReportTHFrm};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'SSP Accounting 5.0';
  Application.CreateForm(TMainDM, MainDM);
  if isLoginOK then
  begin
    Application.CreateForm(TInterfaceDM, InterfaceDM);
    Application.CreateForm(TMainFrm, MainFrm);
    Application.CreateForm(TCM_PopupFrm, CM_PopupFrm);
    Application.CreateForm(TPopupFrm,PopupFrm);

  end;
  Application.Run;

end.
